# Generated by Django 4.2.23 on 2025-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_inventorylevel_remove_inventoryitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('processed', 'Обработан'), ('completed', 'Завершен')], default='active', max_length=20),
        ),
    ]
